@extends('layouts.visitor')
@section('title', 'من نحن | شركة الديوان للاستشارات الهندسية')
@section('description', 'تعرف على رسالة ورؤية وقيم شركة الديوان للاستشارات الهندسية في المدينة المنورة.')
@section('content')
<section class="page-hero"><div class="container"><p class="eyebrow">من نحن</p><h1>شريك هندسي يساعدك على اتخاذ قرار بناء أوضح</h1><p>الديوان شركة استشارات هندسية في المدينة المنورة، تتموضع كمستشار يشرح وينظم قبل أن يبدأ العميل رحلة التصميم والرخصة والتنفيذ.</p></div></section>
<section class="section"><div class="container two-col"><div><p class="eyebrow">نبذة</p><h2 class="section-title">لسنا مجرد مقدم خدمة، بل جهة تنظّم قرارك الهندسي</h2><p class="section-copy">نساعد الأفراد والمطورين والمستثمرين على تحويل الأفكار إلى تصاميم عملية ورخص بناء أوضح، مع مراعاة احتياج العميل، استغلال المساحات، متطلبات الكود السعودي، وتكلفة التنفيذ.</p><div class="pill-list"><span class="pill">المدينة المنورة</span><span class="pill">تصميم ورخص</span><span class="pill">استشارات هندسية</span></div></div><div class="visual-panel"></div></div></section>
<section class="section muted-section"><div class="container"><div class="grid three-grid"><article class="card card-pad"><span class="icon-badge">ر</span><h3>الرؤية</h3><p>أن تكون الديوان من أبرز المكاتب الهندسية في المدينة المنورة عبر تجربة واضحة ومنظمة تساعد العميل على الوصول إلى مشروع قابل للتنفيذ بثقة.</p></article><article class="card card-pad"><span class="icon-badge">م</span><h3>الرسالة</h3><p>نحوّل أفكار العملاء إلى تصاميم عملية ورخص بناء واضحة تراعي الاحتياج والكود السعودي وتكلفة التنفيذ.</p></article><article class="card card-pad"><span class="icon-badge">ق</span><h3>القيم</h3><p>الثقة، الدقة، الوضوح، العملية، والجودة هي القواعد التي تقود كل تواصل ومخرج هندسي.</p></article></div></div></section>
<section class="section"><div class="container"><div class="section-head"><p class="eyebrow">نخدم</p><h2 class="section-title">شرائح عملاء تحتاج قراراً هندسياً واضحاً</h2></div><div class="grid four-grid">@foreach (['أصحاب الأراضي', 'المطورون العقاريون', 'المقاولون', 'الشركات والمنشآت'] as $item)<article class="card card-pad"><span class="icon-badge">{{ $loop->iteration }}</span><h3>{{ $item }}</h3><p>نساعد هذه الفئة على فهم الخدمة المناسبة والمتطلبات والخطوة التالية قبل بدء التنفيذ.</p></article>@endforeach</div></div></section>
@include('partials.final-cta')
@endsection